---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Disabling Swap on all nodes
    shell: |
     swapoff -a
     sed -i '/swap/d' /etc/fstab

  - name: Add IPs to /etc/hosts on master and workers
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"
